"""Generate browser/server legal copies from the same reviewed source."""
import json
import re
from pathlib import Path

def sync_legal_content(root):
    root = Path(root)
    source = json.loads((root/'config/legal-content.json').read_text(encoding='utf-8'))
    browser = {lang:{**{key:values[lang] for key,values in source['legal'].items()},'faqHtml':source['faq'][lang]} for lang in ('de','en','fr')}
    browser_source = 'window.D119Legal = '+json.dumps(browser,ensure_ascii=False)+';\n'
    (root/'assets/legal-content.js').write_text('/* Generated by scripts/sync_legal_content.py. */\n'+browser_source,encoding='utf-8',newline='')
    # Include the reviewed constants in the existing app request, avoiding a
    # blocking extra script request before the mobile archive can hydrate.
    app_path = root/'assets/app.js'
    app = app_path.read_text(encoding='utf-8')
    app = re.sub(r'^/\* D119_CANONICAL_LEGAL_BEGIN \*/\n.*?/\* D119_CANONICAL_LEGAL_END \*/\n', '', app, count=1, flags=re.S)
    prefix = '/* D119_CANONICAL_LEGAL_BEGIN */\n'+browser_source+'/* D119_CANONICAL_LEGAL_END */\n'
    app_path.write_text(prefix+app,encoding='utf-8',newline='')
    (root/'shop-worker/legal-content.js').write_text('// Generated by scripts/sync_legal_content.py.\nexport const LEGAL_VERSION = '+json.dumps(source['version'])+';\nexport const CONTRACT_HTML = '+json.dumps(source['legal']['legalAgbHtml']['de'],ensure_ascii=False)+';\n',encoding='utf-8',newline='')

if __name__ == '__main__':
    sync_legal_content(Path(__file__).resolve().parents[1])
