"""Generate browser/server legal copies from the same reviewed source."""
import json
from pathlib import Path

def sync_legal_content(root):
    root = Path(root)
    source = json.loads((root/'config/legal-content.json').read_text(encoding='utf-8'))
    browser = {lang:{**{key:values[lang] for key,values in source['legal'].items()},'faqHtml':source['faq'][lang]} for lang in ('de','en','fr')}
    (root/'assets/legal-content.js').write_text('/* Generated by scripts/sync_legal_content.py. */\nwindow.D119Legal = '+json.dumps(browser,ensure_ascii=False)+';\n',encoding='utf-8',newline='')
    (root/'shop-worker/legal-content.js').write_text('// Generated by scripts/sync_legal_content.py.\nexport const LEGAL_VERSION = '+json.dumps(source['version'])+';\nexport const CONTRACT_HTML = '+json.dumps(source['legal']['legalAgbHtml']['de'],ensure_ascii=False)+';\n',encoding='utf-8',newline='')

if __name__ == '__main__':
    sync_legal_content(Path(__file__).resolve().parents[1])
